<?php

return [
    'agenda' => [
        'bi-cup-hot' => 'Coffee / break',
        'bi-mic' => 'Microphone / speeches',
        'bi-easel' => 'Presentation',
        'bi-globe' => 'Global / TOEFL',
        'bi-globe2' => 'Globe (alt)',
        'bi-people-fill' => 'Panel / discussion',
        'bi-airplane' => 'Travel',
        'bi-building' => 'Building / venue',
        'bi-person' => 'Speaker',
        'bi-briefcase' => 'Partnership / business',
        'bi-gift' => 'Gift / session',
        'bi-gift-fill' => 'Gift (filled)',
        'bi-book' => 'Book / learning',
        'bi-flag' => 'Closing / flag',
        'bi-flag-fill' => 'Flag (filled)',
        'bi-calendar-check' => 'Closing / calendar',
        'bi-clock' => 'Clock / default',
        'bi-journal-check' => 'Journal',
    ],

    'organizers_stat' => [
        '' => 'None (use custom image)',
        'bi-mortarboard' => 'Mortarboard (students)',
        'bi-mortarboard-fill' => 'Mortarboard filled',
        'bi-people-fill' => 'People',
        'bi-person-bounding-box' => 'Person / invigilator',
        'bi-person-badge' => 'Person badge',
        'bi-person-workspace' => 'Person workspace',
        'bi-building' => 'Building',
        'bi-briefcase' => 'Briefcase',
        'bi-laptop' => 'Laptop',
        'bi-pc-display' => 'PC display',
        'bi-display' => 'Display',
        'bi-award' => 'Award',
        'bi-graph-up' => 'Graph up',
        'bi-globe' => 'Globe',
        'bi-book' => 'Book',
        'bi-calendar-event' => 'Calendar event',
        'bi-mic-fill' => 'Microphone',
        'bi-star-fill' => 'Star',
    ],
];
